apiVersion: v1
kind: Secret
metadata:
  name: vkget-cookies
  namespace: vkget
type: Opaque
stringData:
  cookies.txt: |
    # Netscape HTTP Cookie File
    # REPLACE THIS WITH YOUR EXPORTED cookies.txt
