apiVersion: v1
kind: Service
metadata:
  name: vkget-vpn-gateway
  namespace: vkget
spec:
  selector:
    app: vkget-vpn-gateway
  ports:
    - name: control
      port: 8081
      targetPort: 8081
    - name: socks
      port: 1080
      targetPort: 1080
