CREATE DATABASE IF NOT EXISTS vkget
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'vkget'@'%' IDENTIFIED BY 'CHANGE_ME';

GRANT ALL PRIVILEGES ON vkget.* TO 'vkget'@'%';
FLUSH PRIVILEGES;
